// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-z-85kF01bFSnANBsrgdBdRLRh7OWBQ',
    appId: '1:629395654727:web:9f7a55915672c614f90962',
    messagingSenderId: '629395654727',
    projectId: 'examplanner-77be2',
    authDomain: 'examplanner-77be2.firebaseapp.com',
    storageBucket: 'examplanner-77be2.appspot.com',
    measurementId: 'G-L9VLS6SDFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmi03CEx2DNggvYbKV9lVH74Hxe9n8vM4',
    appId: '1:629395654727:android:0569b0baf9145da9f90962',
    messagingSenderId: '629395654727',
    projectId: 'examplanner-77be2',
    storageBucket: 'examplanner-77be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGc-MYBmG4SfUr2j35JulBeRnVPkVt07s',
    appId: '1:629395654727:ios:df00ef9131b7456df90962',
    messagingSenderId: '629395654727',
    projectId: 'examplanner-77be2',
    storageBucket: 'examplanner-77be2.appspot.com',
    iosBundleId: 'com.example.examPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGc-MYBmG4SfUr2j35JulBeRnVPkVt07s',
    appId: '1:629395654727:ios:0e0b386635577eb5f90962',
    messagingSenderId: '629395654727',
    projectId: 'examplanner-77be2',
    storageBucket: 'examplanner-77be2.appspot.com',
    iosBundleId: 'com.example.examPlanner.RunnerTests',
  );
}
